Added Null throw to signal field isn't defined
doonfrs/pluto_grid_plus pull request #77
Opened 2024-09-18 11:54 UTC by piperun

Not sure if try catch is welcomed, but I stumbled upon:
`null check operator used on a null value` and took a while to debug and find out that it was a null check operator within `state_grid_manager`.

If no try catch I suppose we could do something like:
```dart
for (ref in refColumns){
   if(ref.field == null) {
   //...
   }
}
// rest of code
```

2024-09-18 13:21 UTC, doonfrs requested changes

2024-09-18 13:21 UTC, doonfrs commented on lib/src/manager/pluto_grid_state_manager.dart
> -      throw 'NullThrownError occurred: ${e.toString()}';
why don't you use rethrow, it will keep the exception details

2024-09-18 16:17 UTC, piperun commented on lib/src/manager/pluto_grid_state_manager.dart
> -      throw 'NullThrownError occurred: ${e.toString()}';
My bad, I wasn't sure would be more suitable.

2024-09-18 16:24 UTC, piperun commented on lib/src/manager/pluto_grid_state_manager.dart
> -      throw 'NullThrownError occurred: ${e.toString()}';
I've now added a rethrow instea do of `throw`.

2024-09-18 20:09 UTC, doonfrs commented
If you want to rethrow all exceptions ( general catch ) you don't need to try to catch from the beginning.
what do you think ?

2024-09-19 12:07 UTC, piperun commented
> If you want to rethrow all exceptions ( general catch ) you don't need to try to catch from the beginning. what do you think ?

I think that depends, right now we rethrow all exceptions, but perhaps overtime with enough overhaul there might get to a point where we want to handle certain exceptions in a particular fashion.

I kinda also think it looks cleaner/tells the developer that "this is for exception handling".

2024-10-09 14:21 UTC, closed without merging